# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wine_pb2 as wine__pb2


class WineTasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTasterInfo = channel.unary_unary(
                '/wine.WineTaster/GetTasterInfo',
                request_serializer=wine__pb2.TasterRequest.SerializeToString,
                response_deserializer=wine__pb2.TasterResponse.FromString,
                )


class WineTasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTasterInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WineTasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTasterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasterInfo,
                    request_deserializer=wine__pb2.TasterRequest.FromString,
                    response_serializer=wine__pb2.TasterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wine.WineTaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WineTaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTasterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wine.WineTaster/GetTasterInfo',
            wine__pb2.TasterRequest.SerializeToString,
            wine__pb2.TasterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
